import ::pRectorat::Diplome;

module pMinistere{

	typedef sequence<::pRectorat::Diplome> Referenciel;

	interface IMinistere{
		
		typedef sequence<string> TabRectorat;
		
		readonly attribute Referenciel getReferenciel;	
		readonly attribute TabRectorat getRectorats;
		
	};
};