import ::pRectorat::Voeu;
import ::pRectorat::Etudiant;
import ::pRectorat::Diplome;
import ::pRectorat::EtudiantNonTrouve;

// module pUniversite : systeme de l'universite proposant 1 interface
module pUniversite{
	
	typedef sequence<::pRectorat::Voeu> listePrincipale;
	typedef sequence<::pRectorat::Voeu> listeComplementaire;
	typedef sequence<::pRectorat::Voeu> listeRejet;
	typedef sequence<::pRectorat::Diplome> listePrerequis;
	
	struct Note{
		string semestre;
		float moyenne;
		long position;
		string validation;
	};
	
	typedef sequence<Note> listeNotes;

	//Definition des exception du module Universite
	exception voeuNonTrouve{
		string raison;
	 	::pRectorat::Voeu v;
	};
	
	exception universitaireNonTrouve {
		string raison;
		::pRectorat::Etudiant idE;
	};
	
	exception LicenceNonTrouve{
		string raison;
	};
	
	exception MasterNonTrouve{
		string raison;
	};
	
	interface IUniversite{
	
		// Méthode pour récupérer les candidatures
		//readonly attribute ::pRectorat::Voeu getCandidatures; 
		
		// Opération qui permet de recupere les prerequis d'un diplome
		listePrerequis getListePrerequis(in string dip);
		
		//Lors du changement à la période 3, on doit déclencher le process de vérification automatique
		//Fait appel à la méthode setEtatVoeu distante donc ne renvoie rien
		void verifCandidature (in ::pRectorat::TabVoeux tabVoeux);
		
		// Permet de mettre à disposition les notes des étudiants inscrits dans l'université
		listeNotes getNotes(in ::pRectorat::Etudiant idE) raises (::pRectorat::EtudiantNonTrouve);
	
	};
};

