import ::pRectorat::Diplome;

module pMinistere{

		typedef sequence<::pRectorat::Diplome> Referenciel;
		
		typedef sequence<string> TabRectorat;
		

	interface IMinistere{
		
		readonly attribute Referenciel getReferenciel;	
		readonly attribute TabRectorat getRectorats;
		
		//Opération permettant de connaître la période en cours
		string getPeriodeEnCours();
	};
};