package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;

import pUniversite.IUniversiteImpl;
import pUniversite.universitaireNonTrouve;
import ClientsServeurs.ClientEtudiantGV;
import ClientsServeurs.ClientUniversiteGV;
import GUI.*;

/**
 *
 * @author guilhem
 */
public class ConnexionUniversitaire extends javax.swing.JFrame {

	private static IHM_Universitaire parent;
	//private static Hashtable<String, String> listeEtudiants;
	private static ClientUniversiteGV universite;

	/**
	 * Constructeur IHM de connexion d'un universitaire.
	 * @param pParent
	 * @param pCliUnivGV
	 */
    public ConnexionUniversitaire(IHM_Universitaire pParent, ClientUniversiteGV client) {
    	parent = pParent;
    	ConnexionUniversitaire.universite = client;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titre = new javax.swing.JLabel();
        lb_numUniv = new javax.swing.JLabel();
        lb_mdp = new javax.swing.JLabel();
        tf_numEtu = new javax.swing.JTextField();
        tf_mdp = new javax.swing.JTextField();
        bt_connexion = new javax.swing.JButton();
        bt_quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_titre.setText("Connexion Universitaire");

        lb_numUniv.setText("Login");

        lb_mdp.setText("Mot de passe");

        bt_connexion.setText("Se connecter");
        bt_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					bt_connexionActionPerformed(evt);
				} catch (universitaireNonTrouve e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        bt_quitter.setText("Quitter");
        bt_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lb_titre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_numUniv)
                            .addComponent(lb_mdp))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_numEtu)
                            .addComponent(tf_mdp, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(bt_connexion)
                        .addGap(34, 34, 34)
                        .addComponent(bt_quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titre)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_numUniv)
                    .addComponent(tf_numEtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mdp)
                    .addComponent(tf_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_connexion)
                    .addComponent(bt_quitter))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Btn de connexion d'un universitaire
     * @param evt
     * @throws universitaireNonTrouve 
     */
    private void bt_connexionActionPerformed(java.awt.event.ActionEvent evt) throws universitaireNonTrouve {//GEN-FIRST:event_bt_connexionActionPerformed
    	if (IUniversiteImpl.identifier(this.tf_numEtu.getText(),this.tf_mdp.getText()))
    	{
    		if(IUniversiteImpl.identifier(tf_numEtu.getText(), tf_mdp.getText())){
    			JOptionPane.showMessageDialog(this, "Bienvenue");
    			this.setVisible(false);
        		this.parent.setVisible(true);
        		this.parent.setEnabled(true);
    		}
    		else{
    			JOptionPane.showMessageDialog(this, "Erreur d'identification", "Erreur", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }

    private void bt_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quitterActionPerformed
      this.setVisible(false);
      this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnexionUniversitaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnexionUniversitaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnexionUniversitaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnexionUniversitaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	new ConnexionUniversitaire(parent,universite).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_connexion;
    private javax.swing.JButton bt_quitter;
    private javax.swing.JLabel lb_mdp;
    private javax.swing.JLabel lb_numUniv;
    private javax.swing.JLabel lb_titre;
    private javax.swing.JTextField tf_mdp;
    private javax.swing.JTextField tf_numEtu;
    // End of variables declaration//GEN-END:variables
}
