/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author guilhem
 */
public class IHM_ExaminerCandidature extends javax.swing.JFrame {

    /**
     * Creates new form IHM_ExaminerCandidature
     */
    public IHM_ExaminerCandidature() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_TitreInterface = new javax.swing.JLabel();
        lb_infoEtudiant = new javax.swing.JLabel();
        lb_NomEtudiant = new javax.swing.JLabel();
        lb_UniversiteEtudiant = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_NotesEtudiants = new javax.swing.JTable();
        lb_titreFormationDemandee = new javax.swing.JLabel();
        cb_Decision = new javax.swing.JComboBox();
        lb_titreDecision = new javax.swing.JLabel();
        bt_ValiderDecision = new javax.swing.JButton();
        bt_Quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_TitreInterface.setText("Examination d'une candidature");

        lb_infoEtudiant.setText("Informations de l'étudiant");

        lb_NomEtudiant.setText("Nom :");

        lb_UniversiteEtudiant.setText("Université :");

        tab_NotesEtudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Semestre", "Code Obtention", "Moyenne", "Classement"
            }
        ));
        jScrollPane1.setViewportView(tab_NotesEtudiants);

        cb_Decision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_Decision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_DecisionActionPerformed(evt);
            }
        });

        lb_titreDecision.setText("Decision:");

        bt_ValiderDecision.setText("Valider decision");
        bt_ValiderDecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ValiderDecisionActionPerformed(evt);
            }
        });

        bt_Quitter.setText("Quitter");
        bt_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_QuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(lb_TitreInterface))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_infoEtudiant)
                            .addComponent(lb_NomEtudiant)
                            .addComponent(lb_UniversiteEtudiant)
                            .addComponent(lb_titreFormationDemandee)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(lb_titreDecision))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(cb_Decision, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(bt_ValiderDecision, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(bt_Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_TitreInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_infoEtudiant)
                .addGap(18, 18, 18)
                .addComponent(lb_NomEtudiant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_UniversiteEtudiant)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lb_titreDecision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_Decision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_titreFormationDemandee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ValiderDecision)
                    .addComponent(bt_Quitter))
                .addGap(143, 143, 143))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_DecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_DecisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_DecisionActionPerformed

    private void bt_ValiderDecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ValiderDecisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ValiderDecisionActionPerformed

    private void bt_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_QuitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_QuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHM_ExaminerCandidature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHM_ExaminerCandidature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHM_ExaminerCandidature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHM_ExaminerCandidature.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHM_ExaminerCandidature().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Quitter;
    private javax.swing.JButton bt_ValiderDecision;
    private javax.swing.JComboBox cb_Decision;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_NomEtudiant;
    private javax.swing.JLabel lb_TitreInterface;
    private javax.swing.JLabel lb_UniversiteEtudiant;
    private javax.swing.JLabel lb_infoEtudiant;
    private javax.swing.JLabel lb_titreDecision;
    private javax.swing.JLabel lb_titreFormationDemandee;
    private javax.swing.JTable tab_NotesEtudiants;
    // End of variables declaration//GEN-END:variables
}
